=== carlosjuniorcosta1/Micontes_minicorpus_contos_encantamento/tagging/alignment.dtd
<!-- DTD : WinPitch Corpus -->
<!-- Version : 1 -->
<!ELEMENT Alignment (TimeStamp, WinPitch, Trans, Layer1, Layer2, Layer3, Layer4, Layer5, Layer6, Layer7, Layer8, UNIT* )>
<!ELEMENT TimeStamp (#PCDATA)>
<!ELEMENT WinPitch (#PCDATA)>
<!ELEMENT Trans (#PCDATA)>
<!ELEMENT Layer1 (#PCDATA)>
<!ELEMENT Layer2 (#PCDATA)>
<!ELEMENT Layer3 (#PCDATA)>
<!ELEMENT Layer4 (#PCDATA)>
<!ELEMENT Layer5 (#PCDATA)>
<!ELEMENT Layer6 (#PCDATA)>
<!ELEMENT Layer7 (#PCDATA)>
<!ELEMENT Layer8 (#PCDATA)>
<!ELEMENT UNIT (#PCDATA)>

<!ATTLIST TimeStamp
        Value CDATA #REQUIRED
>

<!ATTLIST WinPitch
        Program CDATA #REQUIRED
        Version CDATA #REQUIRED
>

<!ATTLIST Trans
        version CDATA #REQUIRED
        creationDate CDATA #REQUIRED
        audioFilename CDATA #REQUIRED
        videoFilename CDATA #REQUIRED
        textFilename CDATA #REQUIRED
>

<!ATTLIST Layer1
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer2
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer3
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer4
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer5
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer6
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer7
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer8
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer9
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer10
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer11
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer12
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer13
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer14
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer15
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer16
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer17
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer18
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer19
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer20
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer21
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer22
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer23
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer24
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer25
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer26
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer27
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer28
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer29
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer30
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer31
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer32
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer33
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer34
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer35
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer36
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer37
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer38
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer39
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer40
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer41
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer42
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer43
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer44
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer45
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer46
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer47
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer48
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer49
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer50
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer51
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer52
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer53
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer54
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer55
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer56
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer57
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer58
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer59
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer60
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer61
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer62
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer63
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer64
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer65
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer66
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer67
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer68
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer69
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer70
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer71
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer72
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer73
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer74
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer75
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer76
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer77
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer78
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer79
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer80
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer81
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer82
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer83
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer84
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer85
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer86
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer87
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer88
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer89
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer90
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer91
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer92
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer93
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer94
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer95
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST Layer96
        Name CDATA #REQUIRED
        ID CDATA #REQUIRED
        Short CDATA #REQUIRED
        Color CDATA #REQUIRED
>

<!ATTLIST UNIT
        speaker CDATA #REQUIRED
        startTime CDATA #REQUIRED
        endTime CDATA #REQUIRED
        Channel CDATA #REQUIRED
        Tag CDATA #REQUIRED
>

=== carlosjuniorcosta1/Micontes_minicorpus_contos_encantamento/tagging/MARIA CAçULA MARIA DO MEIO E MARIA MAIS VéIA_2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE Alignment SYSTEM "alignment.dtd">

<Alignment>

<TimeStamp Value="&#x53;&#x61;&#x74;&#x75;&#x72;&#x64;&#x61;&#x79;&#x2c;&#x20;&#x41;&#x75;&#x67;&#x75;&#x73;&#x74;&#x20;&#x31;&#x33;&#x2c;&#x20;&#x32;&#x30;&#x32;&#x32;&#x20;&#x74;&#x69;&#x6d;&#x65;&#x20;&#x31;&#x39;&#x68;&#x20;&#x30;&#x34;&#x6d;&#x20;&#x30;&#x32;&#x73;"/>

<WinPitch Program="Corpus"  Version="Version U2.00"/>


<Layer1 Name="&#x41;&#x4e;&#x54;" ID="&#x4c;&#x61;&#x79;&#x65;&#x72;&#x31;" Short="&#x41;&#x4e;&#x54;" TagName="" TagSet="" Color="RGB(255,255,255)"/>

<UNIT speaker="&#x41;&#x4e;&#x54;" startTime="2.573 s" endTime="7.719 s" Channel="M" Tag="" Rank="1">&#x45;&#x72;&#x61;&#x20;&#x61;&#x20;&#x64;&#x6f;&#x6e;&#x61;&#x20;&#x5b;&#x2f;&#x32;&#x5d;&#x3d;&#x53;&#x43;&#x41;&#x3d;&#x20;&#x65;&#x72;&#x61;&#x20;&#x5b;&#x2f;&#x31;&#x5d;&#x3d;&#x53;&#x43;&#x41;&#x3d;&#x20;&#x61;&#x20;&#x64;&#x6f;&#x6e;&#x61;&#x20;&#x63;&#x61;&#x73;&#x61;&#x64;&#x61;&#x20;&#x2f;&#x3d;&#x43;&#x4f;&#x42;&#x3d;&#x20;&#x65;&#x6c;&#x61;&#x20;&#x74;&#x69;&#x6e;&#x68;&#x61;&#x20;&#x74;&#x72;&#xea;&#x73;&#x20;&#x66;&#x69;&#x6c;&#x68;&#x61;&#x20;&#x2f;&#x2f;&#x3d;&#x43;&#x4f;&#x4d;&#x3d;</UNIT>
<UNIT speaker="&#x41;&#x4e;&#x54;" startTime="11.448 s" endTime="18.794 s" Channel="M" Tag="" Rank="2">&#x61;&#xed;&#x20;&#x2f;&#x3d;&#x41;&#x55;&#x58;&#x3d;&#x20;&#x71;&#x75;&#x61;&#x6e;&#x64;&#x6f;&#x20;&#x70;&#x61;&#x73;&#x73;&#x6f;&#x75;&#x20;&#x2f;&#x3d;&#x53;&#x43;&#x41;&#x3d;&#x20;&#x75;&#x6e;&#x73;&#x20;&#x74;&#x65;&#x6d;&#x70;&#x6f;&#x20;&#x2f;&#x3d;&#x43;&#x4f;&#x42;&#x3d;&#x20;&#x65;&#x6c;&#x61;&#x20;&#x67;&#x61;&#x6e;&#x68;&#x6f;&#x75;&#x20;&#x5b;&#x2f;&#x31;&#x5d;&#x3d;&#x53;&#x43;&#x41;&#x3d;&#x20;&#x67;&#x61;&#x6e;&#x68;&#x6f;&#x75;&#x20;&#x75;&#x6d;&#x20;&#x6d;&#x65;&#x6e;&#x69;&#x6e;&#x6f;&#x20;&#x2f;&#x2f;&#x3d;&#x43;&#x4f;&#x4d;&#x3d;</UNIT>
<UNIT speaker="&#x41;&#x4e;&#x54;" startTime="21.375 s" endTime="40.789 s" Channel="M" Tag="" Rank="3">&#x67;&#x61;&#x6e;&#x68;&#x6f;&#x75;&#x20;&#x75;&#x6d;&#x20;&#x6d;&#x65;&#x6e;&#x69;&#x6e;&#x6f;&#x20;&#x2f;&#x3d;&#x43;&#x4f;&#x42;&#x3d;&#x20;&#x61;&#xed;&#x20;&#x2f;&#x3d;&#x41;&#x55;&#x58;&#x3d;&#x20;&#x65;&#x20;&#x66;&#x61;&#x6c;&#x6f;&#x75;&#x20;&#x63;&#x61;&#x20;&#x5b;&#x2f;&#x31;&#x5d;&#x3d;&#x53;&#x43;&#x41;&#x3d;&#x20;&#x63;&#x6f;&#x6d;&#x20;&#x61;&#x20;&#x4d;&#x61;&#x72;&#x69;&#x61;&#x20;&#x4d;&#x61;&#x69;&#x73;&#x20;&#x76;&#x65;&#x6c;&#x68;&#x61;&#x20;&#x2f;&#x3d;&#x43;&#x4f;&#x42;&#x3d;&#x20;&#x20;&#x76;&#x6f;&#x63;&#xea;&#x20;&#x76;&#x61;&#x69;&#x20;&#x6c;&#xe1;&#x20;&#x2f;&#x3d;&#x53;&#x43;&#x41;&#x5f;&#x72;&#x3d;&#x20;&#x6e;&#x61;&#x20;&#x68;&#x6f;&#x72;&#x74;&#x61;&#x20;&#x2f;&#x3d;&#x43;&#x4f;&#x42;&#x5f;&#x72;&#x3d;&#x20;&#x61;&#x70;&#x61;&#x6e;&#x68;&#x61;&#x20;&#x2f;&#x3d;&#x53;&#x43;&#x41;&#x5f;&#x72;&#x3d;&#x20;&#x75;&#x6d;&#x20;&#x62;&#x6f;&#x74;&#xe3;&#x6f;&#x20;&#x64;&#x65;&#x20;&#x72;&#x6f;&#x73;&#x61;&#x20;&#x2f;&#x3d;&#x43;&#x4f;&#x42;&#x5f;&#x72;&#x3d;&#x20;&#x65;&#x20;&#x74;&#x72;&#x61;&#x7a;&#x20;&#x2f;&#x3d;&#x53;&#x43;&#x41;&#x3d;&#x20;&#x20;&#x74;&#x72;&#xea;&#x73;&#x20;&#x6d;&#x6f;&#x6c;&#x68;&#x6f;&#x20;&#x5b;&#x2f;&#x31;&#x5d;&#x3d;&#x45;&#x4d;&#x50;&#x5f;&#x72;&#x3d;&#x20;&#x74;&#x72;&#xea;&#x73;&#x20;&#x66;&#x6f;&#x6c;&#x68;&#x61;&#x20;&#x64;&#x65;&#x20;&#x63;&#x6f;&#x75;&#x76;&#x65;&#x20;&#x2f;&#x2f;&#x3d;&#x43;&#x4f;&#x4d;&#x5f;&#x72;&#x3d;</UNIT>
<UNIT speaker="&#x41;&#x4e;&#x54;" startTime="41.002 s" endTime="46.202 s" Channel="M" Tag="" Rank="4">&#x70;&#x61;&#x72;&#x61;&#x20;&#x70;&#x6f;&#x64;&#x65;&#x72;&#x20;&#x66;&#x61;&#x7a;&#x65;&#x72;&#x20;&#x5b;&#x2f;&#x32;&#x5d;&#x3d;&#x53;&#x43;&#x41;&#x5f;&#x72;&#x3d;&#x20;&#x6e;&#xf3;&#x73;&#x20;&#x66;&#x61;&#x7a;&#x65;&#x72;&#x20;&#x6e;&#x61;&#x20;&#x68;&#x6f;&#x72;&#x61;&#x20;&#x64;&#x6f;&#x20;&#x62;&#x61;&#x74;&#x69;&#x7a;&#x61;&#x64;&#x6f;&#x20;&#x64;&#x6f;&#x20;&#x6d;&#x65;&#x6e;&#x69;&#x6e;&#x6f;&#x20;&#x2f;&#x3d;&#x43;&#x4f;&#x42;&#x5f;&#x72;&#x3d;&#x20;&#x69;&#x6e;&#x74;&#x65;&#x69;&#x72;&#x61;&#x72;&#x20;&#x63;&#x6f;&#x6d;&#x20;&#x61;&#x73;&#x20;&#x6f;&#x75;&#x74;&#x72;&#x61;&#x20;&#x63;&#x6f;&#x6d;&#x69;&#x64;&#x61;&#x20;&#x2f;&#x2f;&#x3d;&#x43;&#x4f;&#x4d;&#x5f;&#x72;&#x3d;</UNIT>
<UNIT speaker="&#x41;&#x4e;&#x54;" startTime="48.882 s" endTime="50.397 s" Channel="M" Tag="" Rank="5">&#x61;&#xed;&#x20;&#x2f;&#x3d;&#x41;&#x55;&#x58;&#x3d;&#x20;&#x65;&#x6c;&#x61;&#x20;&#x62;&#x61;&#x74;&#x65;&#x75;&#x20;&#x70;&#x61;&#x72;&#x61;&#x20;&#x6c;&#xe1;&#x20;&#x2f;&#x2f;&#x3d;&#x43;&#x4f;&#x4d;&#x3d;</UNIT>
<UNIT speaker="&#x41;&#x4e;&#x54;" startTime="51.049 s" endTime="67.055 s" Channel="M" Tag="" Rank="6">&#x61;&#xed;&#x20;&#x63;&#x68;&#x65;&#x67;&#x6f;&#x75;&#x20;&#x6c;&#xe1;&#x20;&#x2f;&#x3d;&#x43;&#x4f;&#x42;&#x3d;&#x20;&#x61;&#x70;&#x61;&#x6e;&#x68;&#x6f;&#x75;&#x20;&#x2f;&#x20;&#x6f;&#x20;&#x62;&#x6f;&#x74;&#xe3;&#x6f;&#x20;&#x64;&#x65;&#x20;&#x72;&#x6f;&#x73;&#x61;&#x20;&#x2f;&#x20;&#x71;&#x75;&#x61;&#x6e;&#x64;&#x6f;&#x20;&#x65;&#x6c;&#x61;&#x20;&#x66;&#x6f;&#x69;&#x20;&#x70;&#x61;&#x72;&#x61;&#x20;&#x61;&#x70;&#x61;&#x6e;&#x68;&#x61;&#x72;&#x20;&#x6f;&#x20;&#x6d;&#x6f;&#x6c;&#x68;&#x6f;&#x20;&#x64;&#x65;&#x20;&#x63;&#x6f;&#x75;&#x76;&#x65;&#x20;&#x2f;&#x20;&#x6f;&#x20;&#x52;&#x65;&#x69;&#x20;&#x64;&#x6f;&#x20;&#x2f;&#x20;&#x64;&#x6f;&#x73;&#x20;&#x42;&#x6f;&#x69;&#x20;&#x76;&#x65;&#x69;&#x6f;&#x20;&#x2f;&#x20;&#x70;&#x61;&#x73;&#x73;&#x6f;&#x75;&#x20;&#x61;&#x20;&#x6d;&#xe3;&#x6f;&#x20;&#x6e;&#x65;&#x6c;&#x61;&#x20;&#x2f;&#x2f;</UNIT>
<UNIT speaker="&#x41;&#x4e;&#x54;" startTime="67.055 s" endTime="67.492 s" Channel="M" Tag="" Rank="7">&#x61;&#xed;&#x20;&#x63;&#x68;&#x65;&#x67;&#x6f;&#x75;&#x20;&#x6c;&#xe1;&#x20;&#x2f;&#x3d;&#x43;&#x4f;&#x42;&#x3d;&#x20;&#x61;&#x70;&#x61;&#x6e;&#x68;&#x6f;&#x75;&#x20;&#x2f;&#x3d;&#x53;&#x43;&#x41;&#x3d;&#x20;&#x6f;&#x20;&#x62;&#x6f;&#x74;&#xe3;&#x6f;&#x20;&#x64;&#x65;&#x20;&#x72;&#x6f;&#x73;&#x61;&#x20;&#x2f;&#x3d;&#x43;&#x4f;&#x42;&#x3d;&#x20;&#x71;&#x75;&#x61;&#x6e;&#x64;&#x6f;&#x20;&#x65;&#x6c;&#x61;&#x20;&#x66;&#x6f;&#x69;&#x20;&#x70;&#x61;&#x72;&#x61;&#x20;&#x61;&#x70;&#x61;&#x6e;&#x68;&#x61;&#x72;&#x20;&#x6f;&#x20;&#x6d;&#x6f;&#x6c;&#x68;&#x6f;&#x20;&#x64;&#x65;&#x20;&#x63;&#x6f;&#x75;&#x76;&#x65;&#x20;&#x2f;&#x3d;&#x54;&#x4f;&#x50;&#x3d;&#x20;&#x6f;&#x20;&#x52;&#x65;&#x69;&#x20;&#x64;&#x6f;&#x20;&#x2f;&#x3d;&#x53;&#x43;&#x41;&#x3d;&#x20;&#x64;&#x6f;&#x73;&#x20;&#x42;&#x6f;&#x69;&#x20;&#x76;&#x65;&#x69;&#x6f;&#x20;&#x2f;&#x3d;&#x43;&#x4f;&#x42;&#x3d;&#x20;&#x70;&#x61;&#x73;&#x73;&#x6f;&#x75;&#x20;&#x61;&#x20;&#x6d;&#xe3;&#x6f;&#x20;&#x6e;&#x65;&#x6c;&#x61;&#x20;&#x2f;&#x2f;&#x3d;&#x43;&#x4f;&#x4d;&#x3d;</UNIT>
<UNIT speaker="&#x41;&#x4e;&#x54;" startTime="67.968 s" endTime="68.862 s" Channel="M" Tag="" Rank="8">&#x66;&#x6f;&#x69;&#x20;&#x65;&#x6d;&#x62;&#x6f;&#x72;&#x61;&#x20;&#x2f;&#x2f;&#x3d;&#x43;&#x4f;&#x4d;&#x3d;</UNIT>
<UNIT speaker="&#x41;&#x4e;&#x54;" startTime="73.556 s" endTime="77.090 s" Channel="M" Tag="" Rank="9">&#x61;&#xed;&#x20;&#x2f;&#x3d;&#x41;&#x55;&#x58;&#x3d;&#x20;&#x66;&#x69;&#x63;&#x6f;&#x75;&#x20;&#x61;&#x20;&#x5b;&#x2f;&#x31;&#x5d;&#x3d;&#x53;&#x43;&#x41;&#x3d;&#x20;&#x61;&#x20;&#x4d;&#x61;&#x72;&#x69;&#x61;&#x20;&#x64;&#x6f;&#x20;&#x4d;&#x65;&#x69;&#x6f;&#x20;&#x2f;&#x2f;&#x3d;&#x43;&#x4f;&#x4d;&#x3d;</UNIT>
<UNIT speaker="&#x41;&#x4e;&#x54;" startTime="77.294 s" endTime="86.788 s" Channel="M" Tag="" Rank="10">&#xf4;&#x20;&#x6d;&#x69;&#x6e;&#x68;&#x61;&#x20;&#x69;&#x72;&#x6d;&#xe3;&#x20;&#x2f;&#x20;&#x6d;&#x61;&#x20;&#x5b;&#x2f;&#x31;&#x5d;&#x20;&#x26;&#x68;&#x65;&#x20;&#x2f;&#x20;&#x76;&#x61;&#x69;&#x20;&#x6c;&#xe1;&#x20;&#x6e;&#x61;&#x20;&#x5b;&#x2f;&#x31;&#x5d;&#x20;&#x6e;&#x61;&#x20;&#x68;&#x6f;&#x72;&#x74;&#x61;&#x20;&#x61;&#x70;&#x61;&#x6e;&#x68;&#x61;&#x20;&#x6f;&#x20;&#x6d;&#x6f;&#x6c;&#x68;&#x6f;&#x20;&#x64;&#x65;&#x20;&#x63;&#x6f;&#x75;&#x76;&#x65;&#x20;&#x65;&#x20;&#x6f;&#x20;&#x62;&#x6f;&#x74;&#xe3;&#x6f;&#x20;&#x64;&#x65;&#x20;&#x72;&#x6f;&#x73;&#x61;&#x20;&#x2f;&#x3d;&#x43;&#x4f;&#x42;&#x5f;&#x72;&#x3d;&#x20;&#x71;&#x75;&#x65;&#x20;&#x73;&#x75;&#x61;&#x20;&#x69;&#x72;&#x6d;&#xe3;&#x20;&#x74;&#x69;&#x76;&#x65;&#x72;&#x20;&#x6c;&#xe1;&#x20;&#x63;&#xe9;&#x20;&#x74;&#x72;&#x61;&#x7a;&#x20;&#x2b;&#x3d;&#x45;&#x4d;&#x50;&#x5f;&#x72;&#x3d;</UNIT>
<UNIT speaker="&#x41;&#x4e;&#x54;" startTime="86.788 s" endTime="87.068 s" Channel="M" Tag="" Rank="11">&#xf4;&#x20;&#x6d;&#x69;&#x6e;&#x68;&#x61;&#x20;&#x69;&#x72;&#x6d;&#xe3;&#x20;&#x2f;&#x20;&#x6d;&#x61;&#x20;&#x5b;&#x2f;&#x31;&#x5d;&#x20;&#x26;&#x68;&#x65;&#x20;&#x2f;&#x20;&#x76;&#x61;&#x69;&#x20;&#x6c;&#xe1;&#x20;&#x6e;&#x61;&#x20;&#x5b;&#x2f;&#x31;&#x5d;&#x20;&#x6e;&#x61;&#x20;&#x68;&#x6f;&#x72;&#x74;&#x61;&#x20;&#x61;&#x70;&#x61;&#x6e;&#x68;&#x61;&#x20;&#x6f;&#x20;&#x6d;&#x6f;&#x6c;&#x68;&#x6f;&#x20;&#x64;&#x65;&#x20;&#x63;&#x6f;&#x75;&#x76;&#x65;&#x20;&#x65;&#x20;&#x6f;&#x20;&#x62;&#x6f;&#x74;&#xe3;&#x6f;&#x20;&#x64;&#x65;&#x20;&#x72;&#x6f;&#x73;&#x61;&#x20;&#x2f;&#x3d;&#x43;&#x4f;&#x42;&#x5f;&#x72;&#x3d;&#x20;&#x71;&#x75;&#x65;&#x20;&#x73;&#x75;&#x61;&#x20;&#x69;&#x72;&#x6d;&#xe3;&#x20;&#x74;&#x69;&#x76;&#x65;&#x72;&#x20;&#x6c;&#xe1;&#x20;&#x63;&#xe9;&#x20;&#x74;&#x72;&#x61;&#x7a;&#x20;&#x2b;&#x3d;&#x45;&#x4d;&#x50;&#x5f;&#x72;&#x3d;</UNIT>
